letters = ["a", "b", "c", "d", "e", "f"]

# ADD:
# ADD ITEM TO THE END OF THE LIST WE SHOULD USE APPEND() METHOD
letters.append("g")
print(letters)

# TO ADD ITEM IN SPECIFIC POSITION WE SHOULD USE INSORT METHOD

letters.insert(0, "-")
print(letters)

# REMOVING OBJECT
# IF WE DON'T PROVIDE ANY INDEX IT WILL REMOVE ITEM FORM THE END
letters.pop()
print(letters)

# TO REMOVE ITEM FROM SPECIFIC POSITION OR INDEX
letters.pop(0)
print(letters)
# WE DO NOT HAVE "d" IN OUTPUT BECAUSE IT IS ALREADY REMOVED

# TO REMOVE AN OBJECT BUT YOU DON'T KNOW ITS INDEX
letters.remove("b")
print(letters)
# IT WILL REMOVE ONLY THE FIRST OCCURRENCE OF THE OBJECT
# TO REMOVE MULTIPLE OCCURRENCE OF THE OBJECT YOU HAVE RUN A LOOP
# (OR)
# POP() METHOD WILL DELETE SINGLE ITEM
# DEL DELETE METHOD WILL REMOVE A RANGE OF ITEMS
# TO REMOVE ALL OBJECT WE USE CLEAR METHOD
del letters[0:3]
print(letters)

letters.clear()
print(letters)
