print(type(5))
print(type(range(5)))  # THE RANGE PROGRAMME RETURNS AN OBJECT OF TYPE RANGE
# HERE RANGE IS COMPLEX TYPES NOT PRIMITIVE TYPES
# IT IS ITERABLE
# CAN BE USED IN LOOP
# STRINGS ARE ALSO ITERABLE
for x in "Python":
    print(x, end=" ")

# CAN BE USED FOR LIST OF OBJECTS

for x in [1, 2, 3, 4, 5]:
    print(x, end=" ")
# IN EACH OBJECT IN LIST ITERABLE
